### PR TITLE
fixed memory problems in g2_addfield() in error conditions, test, and clean up, error handling of g2_getfld()

### LINKED ISSUE #160: memory leak in g2_getfld() if errors occur reading message
In g2_getfld() we have:

`    lgfld = malloc(sizeof(gribfield));
`
Later in the code:

```
    if (istart == -1) {
        printf("g2_getfld:  Beginning characters GRIB not found.\n");
        ierr = 1;
        return(ierr);
    }

```
and

```
    if (istart == -1) {
        printf("g2_getfld:  Beginning characters GRIB not found.\n");
        ierr = 1;
        return(ierr);
    }

```
and 

```
    /*  Currently handles only GRIB Edition 2. */
    if (ver != 2) {
        printf("g2_getfld: can only decode GRIB edition 2.\n");
        ierr = 2;
        return(ierr);
    }

```
and there are some other returns for error conditions. Note that they are not freeing the memory allocated in lgfld. There are (commented out) tests for this in tst_g2_addfield.c.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #160 
Part of #8.

Fix memory leak on any error in g2_addfield(). 

Test, and clean up, error handling of g2_getfld().

### CODE REVIEW

File: src/g2_getfld.c [hunk 1]
```diff
@@ -338,53 +340,53 @@ g2_getfld(unsigned char *cgrib, g2int ifldnum, g2int unpack, g2int expand,
...
             {
-                have7 = 1;
-                /*  If bitmap is used with this field,  expand data field */
-                /*  to grid, if possible. */
-                if (lgfld->ibmap != 255 && lgfld->bmap != 0)
+                if (expand == 1)
                 {
-                    if (expand == 1)
+                    n = 0;
+                    newfld = calloc(lgfld->ngrdpts, sizeof(g2float));
```
Comment (BrianCurtis-NOAA) [inline src/g2_getfld.c:362]: should newfld have a free() ? i see it's allocated but not free'd

Comment (Hang-Lei-NOAA) [reply src/g2_getfld.c:362]: This should be fine. C allow this.

**Review by Hang-Lei-NOAA — APPROVED** [review]

File: src/g2_getfld.c (hunk 1 above)
Comment (edwardhartnett) [reply src/g2_getfld.c:362]: Indeed it must be freed! But look further in the code:

```
               if (expand == 1)
                {
                    n = 0;
                    newfld = calloc(lgfld->ngrdpts, sizeof(g2float));
                    for (j = 0; j < lgfld->ngrdpts; j++)
                    {
                        if (lgfld->bmap[j] == 1)
                            newfld[j] = lgfld->fld[n++];
                    }
                    free(lgfld->fld);
                    lgfld->fld = newfld;
                    lgfld->expanded = 1;
```
So the address is assigned to the fld member of the struct pointed to by lgfld. Later this is freed with a g2_free(), which frees all the memory allocated to any member of this struct.
