### PR TITLE
Fix bug with g2c_aecpackf()/g2c_aecpackd() and add test

### LINKED ISSUE #511: g2c_aecpackf() and g2c_aecpackd() only work for constant data values
I believe it's due to this part here:
```c
    ret = aecpack_int(fld, 0, width8, height8, idrstmpl8, cpack, &lcpack8, 0);
    if (!ret)
    {
        for (i = 0; i < G2C_AEC_DRS_TEMPLATE_LEN; i++)
            idrstmpl[i] = (int)idrstmpl8[i];
        *lcpack = (g2int)lcpack8;
    }
``` 
For non-constant data, ret is updated like this in aecpack_int() :
```c
        ret = enc_aec(ctemp, ctemplen, nbits, ccsds_flags, ccsds_block_size, ccsds_rsi, cpack, lcpack);
        if (ret < 0)
        {
            if (verbose) printf("aecpack: ERROR Packing AEC = %d\n",ret);
            nbits = 0;
            *lcpack = 0;
        }

        *lcpack = ret;
``` 
So after exiting aecpack_int(), idrstmpl isn't getting updated because ret > 0.

Currently, we're only testing g2c_aecpackd with constant data.

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Fixes #511

### CODE REVIEW

File: tests/tst_aec.c [hunk 1]
```diff
@@ -125,6 +125,35 @@ main()
...
+
+	/* Unpack the data. */
+	ret = g2c_aecunpackd(cpack, len, (int *)idrstmpl, ndpts, fld_in);
+	if (ret < 0)
+	    return G2C_ERROR;
+
+	for (i = 0; i < DATA_LEN; i++)
+	{
+	    /* printf("%g %g\n", fld[i], fld_in[i]); */
+	    if (fld[i] != fld_in[i])
```
Comment (AlexanderRichert-NOAA) [inline tests/tst_aec.c]: Minor quibble, but should this be getting compared within some small tolerance since it's floating-point data?

**Review by AlexanderRichert-NOAA — APPROVED** [review]

**Review by edwardhartnett — APPROVED** [review]

**Comment by edwardhartnett** [comment]
Is this ready to merge?

**Comment by AlysonStahl-NOAA** [comment]
It is now. I just added those fixes to the value comparison.
