### PR TITLE
fix the inmem issue casued by jasper lib upgrade

### LINKED ISSUE #10: G2C cannot  build with new version jasper lib
The g2c lib cmake build cannot build with jasper version after 1.900.1. This is caused by the upgraded jasper lib does not support inmem union category. Therefore, it reports error on line 124 of enc_jpeg2000.c file.
The line use inmem category should be comment out to build with upgraded jasper lib.

It is linked with the pull request 
fix the inmem issue casued by jasper lib upgrade (#9)

### PR DESCRIPTION
**Pull request by Hang-Lei-NOAA**
SInce jasper no long support inmem union, we remove it to stop the compiling bug caused by it.
The testing of compiling is kept on 
/gpfs/dell2/emc/modeling/noscrub/Hang.Lei/libs/github/NCEPLIBS-g2c
Could please the code manager create a new tag after the review?
Thanks,

### CODE REVIEW

File: src/enc_jpeg2000.c [hunk 1]
```diff
@@ -5,6 +5,7 @@
 #include <stdio.h>
 #include <stdlib.h>
 #include "grib2.h"
+#include <string.h>
```
Comment (kgerheiser) [inline src/enc_jpeg2000.c]: Why did you add this?

Comment (Hang-Lei-NOAA) [reply src/enc_jpeg2000.c]: Yes, this should be removed

Comment (Hang-Lei-NOAA) [reply src/enc_jpeg2000.c]: updated for further review

**Review by kgerheiser — APPROVED** [review]
I approve. This same change was made in the regular g2 library.

**Comment by edwardhartnett** [comment]
Is there an issue describing this change? If not, can you add one?

**Comment by Hang-Lei-NOAA** [comment]
Okay, I will add one.
