### PR TITLE
Replace call to strsep() in g2c_csv_init() with local implementation to support Windows with clang

### LINKED ISSUE #555: use of strsep() fails to find function definition in strings.h on Windows with clang
I get this warning:

D:/a/NCEPLIBS-g2c/NCEPLIBS-g2c/g2c/src/g2ccsv.c:222:23: error: implicit declaration of function 'strsep'; did you mean 'strset'? [-Wimplicit-function-declaration]
  222 |                 tmp = strsep(&buf, "\"");
      |                       ^~~~~~
      |                       strset
D:/a/NCEPLIBS-g2c/NCEPLIBS-g2c/g2c/src/g2ccsv.c:222:21: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  222 |                 tmp = strsep(&buf, "\"");
      |                     ^
D:/a/NCEPLIBS-g2c/NCEPLIBS-g2c/g2c/src/g2ccsv.c:223:21: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  223 |                 tmp = strsep(&buf, "\"");
      |                     ^
D:/a/NCEPLIBS-g2c/NCEPLIBS-g2c/g2c/src/g2ccsv.c:225:21: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  225 |                 tmp = strsep(&buf, ",");
      |                     ^
D:/a/NCEPLIBS-g2c/NCEPLIBS-g2c/g2c/src/g2ccsv.c:229:21: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  229 |                 tmp = strsep(&buf, ",");
      |                     ^

Looks like we should use strtok() instead. See https://stackoverflow.com/questions/58244300/getting-the-error-undefined-reference-to-strsep-with-clang-and-mingw.

@AlysonStahl-NOAA can you convert this code to strtok()? Hopefully sometime this week?

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Fixes #555

### CODE REVIEW

File: src/g2ccsv.c [hunk 1]
```diff
@@ -177,6 +177,32 @@ g2c_find_entry(char *desc, G2C_CODE_TABLE_T *table)
...
+ *
+ * @param stringp The address of a pointer to string to be separated.
+ * This value is overwritten with the value past the delimiter.
+ * @param delim Characters that delimit the tokens.
+ *
+ * @author Alyson Stahl @date 11/6/24
+ *
+ * @return a pointer to the original value of stringp
+ */
+char *
```
Comment (edwardhartnett) [inline src/g2ccsv.c]: Can you make this function static?

Then it will only be visible to this file.

**Review by edwardhartnett — APPROVED** [review]
